# 协议

python中有许多协议，用户为自己的数据对象实现协议，就能像使用内建对象一样使用自己的数据对象。

运算符重载就是一种协议，用户实现`__add__`方法，就相当于为自己的对象实现了`+`操作，不必显式调用`__add__`方法。协议本质上就是一种语法糖，它可以使代码看起来更加优美，更容易书写。

## 迭代器协议

用于访问容器数据

### 实现方法：

* `__iter__`：返回一个可迭代对象（具有`__next__`方法）
* `__next__`：返回下一个元素，迭代完成时抛出StopIteration异常

### 适用范围

* 用于`for…in`循环
* 手动`next`

```python
class iterator:
    def __init__(self):
        self.i = 0

    def __iter__(self):
        return self

    def __next__(self):
        self.i += 1
        if self.i < 5:
            return self.i
        raise StopIteration

for i in iterator():
    print(i)

it = iterator()
print(next(it))
print(next(it))

# output
1
2
3
4
1
2
```

## With 上下文协议

用于处理文件读写之类的资源性活动。即使发生异常，`__exit__`方法仍会调用，该方法的三个参数包含异常信息。

### 实现方法

* `__enter__`：返回一个资源
* `__exit__(self, exc_type, exc_val, exc_tb)`：释放资源

```python
class File:
    def __init__(self, filename):
        self.filename = filename

    def __enter__(self):
        self.fp = open(self.filename)
        return self.fp

    def __exit__(self, exc_type, exc_val, exc_tb):
        print(exc_type)
        print(exc_val)
        print(exc_tb)
        self.fp.close()


with File("test.py") as f:
    raise Exception("trouble")
    for line in f:
        print(line)

# output
<class 'Exception'>
trouble
<traceback object at 0x000001DADD632088>
Traceback (most recent call last):
  File "type.py", line 18, in <module>
    raise Exception("trouble")
Exception: trouble
```

